Support  for incoming data stage
pharaun13/maleficarum-auth pull request #1
Opened 2017-09-28 10:07 UTC by twarezak

2017-09-28 10:55 UTC, pharaun13 requested changes

2017-09-28 10:55 UTC, pharaun13 commented on src/Auth/Initializer/Initializer.php
> +                        isset($authId) ? $auth->setId($authId) : $auth->setId('');
Do not set an empty string if the value is unavailable - leave it as a null.

2017-09-28 10:59 UTC, pharaun13 commented on src/Auth/Initializer/Initializer.php
> +                        isset($authId) ? $auth->setId($authId) : $auth->setId('');
What is that Session interface and why is it in the auth repository?

2017-10-05 09:28 UTC, paq85 approved these changes

2017-10-09 13:26 UTC, merged